### ISSUE TITLE
jsfest.com is down

### ISSUE THREAD

**Issue by thefoxis** [jsfest/jsfest.github.io#2]
I think it might be down for couple days now (it times out). @mikeal can you check please? :)

**Comment by mikeal** [comment]
oh wow, i wonder why, it's just gh-pages :(

**Comment by thefoxis** [comment]
maybe something with the files got borked, somehow? it's still timing out :cry:

**Comment by mikeal** [comment]
I'm pretty sure this is because the images are too big and so GH is just shutting it down.

Would love it if some awesome designer would just make a better site :) Adding you as a collaborator now BTW :)

**Comment by thefoxis** [comment]
Hahaha, you know how to roll :doughnut: 

Will have a look this week :)
